<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Combo Bags</name>
   <tag></tag>
   <elementGuidId>0d9562a6-3cc7-41d8-a06a-7c91f56a4086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26722']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26722 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>914e2bcf-c386-462d-bec7-8cab89fe06e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/combo-bags/</value>
      <webElementGuid>fe30f22e-d599-4cb8-97a1-be5341695757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Combo Bags</value>
      <webElementGuid>3de22152-3092-4ee0-87f2-614c48888f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26722&quot;)/a[1]</value>
      <webElementGuid>ae94462b-4bcd-495c-9b22-469742ca167d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26722']/a</value>
      <webElementGuid>82c3ddc9-9649-46f8-a8d1-c00761d41f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Combo Bags')]</value>
      <webElementGuid>132d32f1-bccd-40a7-967e-39a5837faef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/combo-bags/')]</value>
      <webElementGuid>1a6c3b06-b282-4e35-a5b3-d1da47db39cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[5]/a</value>
      <webElementGuid>a64f88fd-3d8c-4e99-9dca-753aff43c2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/combo-bags/' and (text() = 'Combo Bags' or . = 'Combo Bags')]</value>
      <webElementGuid>3b765967-a407-45c8-b19b-cf3791907277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
