<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Chair</name>
   <tag></tag>
   <elementGuidId>963cc381-8850-4355-8acf-84dda1e470df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26662']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26662 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3335f975-565f-49e7-9834-a18933b12868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-chair/</value>
      <webElementGuid>1f6d05ae-1670-40d3-896c-43bcbb475cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Chair</value>
      <webElementGuid>0691a5d5-f8e7-462b-afa9-74604d769542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26662&quot;)/a[1]</value>
      <webElementGuid>9a1f0ea7-10e2-47f2-8036-5052e52fc07b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26662']/a</value>
      <webElementGuid>2e806da3-ede7-474b-8fcc-ba35783f81ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Chair')]</value>
      <webElementGuid>665bc27c-f2d7-4f72-9c8c-8148b5d9bc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-chair/')]</value>
      <webElementGuid>cc7fc64b-1033-4a15-b0be-c5a092f4c393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul/li/a</value>
      <webElementGuid>5215643a-2d9c-4a68-87a0-a13bcfa0967d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-chair/' and (text() = 'Bamboo Chair' or . = 'Bamboo Chair')]</value>
      <webElementGuid>de9cbc0a-a457-4431-9a26-d26b329c3105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
