<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Furniture</name>
   <tag></tag>
   <elementGuidId>4d2c3288-1188-4af9-afa3-f912f2f67505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26661']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26661 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70514eb1-3a5e-4ff2-9395-00baaaeae873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-furniture/</value>
      <webElementGuid>a4a06da2-ebf9-4815-a7cf-b9cba546313e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Furniture</value>
      <webElementGuid>dc57e565-9bb2-481a-81d5-4048adff382f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26661&quot;)/a[1]</value>
      <webElementGuid>5558ffbb-e41c-4974-a222-b41531e55581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26661']/a</value>
      <webElementGuid>9cc41bc2-2fb1-443c-a69f-496a54d05bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Furniture')]</value>
      <webElementGuid>b1eb7757-c1ee-4a5b-84b5-59aef1f77543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-furniture/')]</value>
      <webElementGuid>8dc77d02-0856-42cd-825e-4a50310b5006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>c468aef9-68d9-4c4d-863c-c3e55839ade4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-furniture/' and (text() = 'Bamboo Furniture' or . = 'Bamboo Furniture')]</value>
      <webElementGuid>5e295f0d-87b6-4463-b69e-ef937f60de0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
