<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Natural Mudha</name>
   <tag></tag>
   <elementGuidId>20cb7e3a-bcb1-4538-b94d-b2436aa9ce7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26668']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26668 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c51a0046-efad-4472-8a2c-a31f7bb6c30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/natural-mudha/</value>
      <webElementGuid>902195b2-ce3e-4274-8ae8-40a4549be196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Natural Mudha</value>
      <webElementGuid>5f66353b-43a1-4051-b8a0-5eac0af364b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26668&quot;)/a[1]</value>
      <webElementGuid>ecd62166-e134-45a1-95c4-58593d631035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26668']/a</value>
      <webElementGuid>2a00540a-951f-45c0-be6a-51e6ae9bddd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Natural Mudha')]</value>
      <webElementGuid>3d92284e-91f2-4d27-bd57-58e5c6e423b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/natural-mudha/')]</value>
      <webElementGuid>1b3a5702-006a-4af8-9cb8-d7954b019120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>6ace2ce1-8c56-48de-862e-614230083cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/natural-mudha/' and (text() = 'Natural Mudha' or . = 'Natural Mudha')]</value>
      <webElementGuid>0f22067b-2fa7-4337-8e79-abf7c25fcd72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
