<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Double Tapestry</name>
   <tag></tag>
   <elementGuidId>ca85b0b9-d421-40e1-865a-8e3977787125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26728']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26728 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06dc14ec-85e6-42c4-abfa-25abf1e29bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/double-tapestry/</value>
      <webElementGuid>a0958535-6ebe-48d7-804f-579473c83db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Double Tapestry</value>
      <webElementGuid>42aff19e-244b-4eab-9509-06c42cca9a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26728&quot;)/a[1]</value>
      <webElementGuid>a40802d9-1f84-4326-badf-a1aea8ee1538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26728']/a</value>
      <webElementGuid>70205d76-e960-4565-9e0b-fc3de459bc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Double Tapestry')]</value>
      <webElementGuid>c52f5657-dd8d-40fb-9190-4814ce8855da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/double-tapestry/')]</value>
      <webElementGuid>d0191330-c15d-4ce0-88f6-de8cba987063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[3]/a</value>
      <webElementGuid>e5a0f093-b940-41d7-942d-30036e6ce7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/double-tapestry/' and (text() = 'Double Tapestry' or . = 'Double Tapestry')]</value>
      <webElementGuid>cf4080fd-afaf-492f-9bc3-3561e8f10c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
