<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Placemats  Runners</name>
   <tag></tag>
   <elementGuidId>29661402-477c-4806-8281-660298eefae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26711']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26711 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>46c3a293-1e96-441e-a8ce-1d572ad501a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/placemats-runners/</value>
      <webElementGuid>88a19283-a6d1-4a2a-a9cc-f29e6661f6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Placemats &amp; Runners</value>
      <webElementGuid>7e703000-50fd-470b-93c4-3b2a0bbebdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26711&quot;)/a[1]</value>
      <webElementGuid>be4582b9-db71-497e-9281-03fb22a35067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26711']/a</value>
      <webElementGuid>074e7763-0dfe-41db-9b6e-f2900958663f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Placemats &amp; Runners')]</value>
      <webElementGuid>5e22ad33-66fe-44a3-8fa5-814079841906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/placemats-runners/')]</value>
      <webElementGuid>a7ec578c-165a-4330-84dc-b35ddbfd2c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[2]/a</value>
      <webElementGuid>1ba3d5e3-d142-438f-b40e-b96bc8776b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/placemats-runners/' and (text() = 'Placemats &amp; Runners' or . = 'Placemats &amp; Runners')]</value>
      <webElementGuid>674fccdd-8f00-44e1-aa77-f82091082238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
