<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Double Bedsheet</name>
   <tag></tag>
   <elementGuidId>d68efeb7-368f-4216-a3bb-5b81d9758be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26713']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26713 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11de187a-0ebf-4139-8287-ad130c752843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/double-bedsheet/</value>
      <webElementGuid>0e5f9fdc-4e06-4ef7-aa00-b6cce89a8251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Double Bedsheet</value>
      <webElementGuid>f03802f6-d54a-42ae-8d45-18026da25233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26713&quot;)/a[1]</value>
      <webElementGuid>de310ede-a39e-4a2e-9c0f-5d0f21c9877e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26713']/a</value>
      <webElementGuid>528a0813-9214-4f55-9ae2-30c7dc1ec46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Double Bedsheet')]</value>
      <webElementGuid>4a0e311a-6aba-46f4-97ba-a07c87eb3ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/double-bedsheet/')]</value>
      <webElementGuid>700aa64c-94e1-4d36-b8ba-c3f6f160f68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[3]/ul/li[2]/a</value>
      <webElementGuid>014ff938-c9f2-4848-bd7b-32ce2d20fcd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/double-bedsheet/' and (text() = 'Double Bedsheet' or . = 'Double Bedsheet')]</value>
      <webElementGuid>ee83d6ad-7676-4823-aafe-3b435155231e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
