<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>16503cf5-086e-4f03-b1b6-1a8941ef5bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qlwapp']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.qlwapp-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a3352fd-ee88-4ba1-9dee-018e8b9f7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qlwapp-toggle</value>
      <webElementGuid>e85bc6c3-fa70-45eb-bd45-f66f3031c288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>b7a1b597-6aee-43d9-a1db-415abf469581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-phone</name>
      <type>Main</type>
      <value>8373915568</value>
      <webElementGuid>61259fe5-c655-4f9f-947f-85ccf6a30db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-message</name>
      <type>Main</type>
      <value>https://craferia.com</value>
      <webElementGuid>fbc6499a-27fd-4b74-b87f-020eac1a6adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0755dbcd-37ae-48dd-8229-d0f4981d2507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b364ae8-3f11-4da8-8434-a540ed73bc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d3988e8e-f199-4200-9f51-bf73d52a31ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							
						×
					</value>
      <webElementGuid>9721fe67-df77-441a-b3c3-7e3d15146840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qlwapp&quot;)/div[@class=&quot;qlwapp-container&quot;]/a[@class=&quot;qlwapp-toggle&quot;]</value>
      <webElementGuid>233cdc28-66b3-43b0-abd8-2f6a7c6c8960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qlwapp']/div/a</value>
      <webElementGuid>77f59dfc-3fba-4d64-8c66-f4777ab5d26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>f0609a95-263e-4a71-987f-5b05f12d5f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
							
						×
					' or . = '
							
						×
					')]</value>
      <webElementGuid>5ef23d5a-1599-40e0-8715-b75c4bc81339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
