<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to cart</name>
   <tag></tag>
   <elementGuidId>05b5b6f8-6889-4ff1-80f0-756a14ce27b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div[4]/ul/li/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wp-block-button__link.add_to_cart_button.ajax_add_to_cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59a4a3d3-3645-42fe-968f-907f831bf173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?add-to-cart=29547</value>
      <webElementGuid>68f174d5-f92d-4b10-8db0-8ec0021aeb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add “Wooden Bench Charpai with 4 Mudda Stools for living room, balcony, garden, cafe &amp; restaurants” to your cart</value>
      <webElementGuid>5b3f4987-0a38-4519-8d46-a2b47f7547ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>64403ac6-fa12-41fc-8b7d-f5074d204e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>29547</value>
      <webElementGuid>b7493ef6-c253-4a4a-961e-74420b93a77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>MUDHA-219</value>
      <webElementGuid>e66d2d29-ef5f-4c84-b3d7-6f77de9ef4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>d1744b6d-01db-429a-887d-e8360b4fa91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-button__link  add_to_cart_button ajax_add_to_cart</value>
      <webElementGuid>3d0def68-4027-4120-9c8f-a94a77635cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>15029a4c-8ce6-4f5e-a91b-4e7568ced8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;page-description&quot;]/div[@class=&quot;wc-block-grid wp-block-product-category wc-block-product-category has-5-columns has-aligned-buttons&quot;]/ul[@class=&quot;wc-block-grid__products&quot;]/li[@class=&quot;wc-block-grid__product&quot;]/div[@class=&quot;wp-block-button wc-block-grid__product-add-to-cart&quot;]/a[@class=&quot;wp-block-button__link  add_to_cart_button ajax_add_to_cart&quot;]</value>
      <webElementGuid>b68ef903-127a-4865-81f4-2a9a4e25538c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div[4]/ul/li/div[2]/a</value>
      <webElementGuid>4134bbc7-9050-486c-a052-6cefdf74d656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add to cart')]</value>
      <webElementGuid>35390b89-4f10-4714-b9cf-df81e8f3eef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?add-to-cart=29547')]</value>
      <webElementGuid>db78206d-5563-4b3f-b9a8-b022adcc7e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>65948b8d-1421-4edd-b4a7-a6f15e1a8e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?add-to-cart=29547' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>f41f598c-188f-4c6a-8eaf-8abf6ef02df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
