<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click More</name>
   <tag></tag>
   <elementGuidId>10ca79a0-8b14-4d2d-9a0b-82a5e953981d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dswbm-sliders-26847']/ul/li/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shop-now-btn > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7343e7a9-c888-46f6-a844-f952a72d5100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/showpieces-figurines/</value>
      <webElementGuid>7edfc0d1-f7bb-48d6-be09-7d66feb6f57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e69cb7cd-6e71-48da-9ad6-0466507f0a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click More</value>
      <webElementGuid>079726a6-9fd0-4917-9063-9ee9c07d4f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dswbm-sliders-26847&quot;)/ul[@class=&quot;wbm-slider&quot;]/li[@class=&quot;term-list&quot;]/div[@class=&quot;term-content&quot;]/div[@class=&quot;shop-now-btn&quot;]/a[1]</value>
      <webElementGuid>a316370b-e914-4a36-b7a2-62d89810e4d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dswbm-sliders-26847']/ul/li/div[2]/div/a</value>
      <webElementGuid>ec9441ca-4ce5-48e1-bdb1-c37d1dd2b982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Click More')]</value>
      <webElementGuid>f75f10b7-b13a-4661-b21c-148adeea5403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://craferia.com/showpieces-figurines/')])[5]</value>
      <webElementGuid>7fc8521f-884b-4e5c-90d5-ac4df889f527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[2]/div/a</value>
      <webElementGuid>71529224-1c89-4129-86fd-6063da81a755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/showpieces-figurines/' and (text() = 'Click More' or . = 'Click More')]</value>
      <webElementGuid>a7b770c1-1565-4da8-a3c2-ecea4a746173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
