<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_INFORMATION</name>
   <tag></tag>
   <elementGuidId>f89c68c7-a438-405a-8589-b798c42081d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-10']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#block-10 > h2.wp-block-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d4fd4389-2510-4688-9a52-0474817f79b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-heading</value>
      <webElementGuid>cf2333db-c51a-44e1-8b16-cf739c5fc99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INFORMATION</value>
      <webElementGuid>ab243a66-b311-4d10-97db-2b8725bc4b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-10&quot;)/h2[@class=&quot;wp-block-heading&quot;]</value>
      <webElementGuid>b4035f61-5541-4055-871d-460864a87480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-10']/h2</value>
      <webElementGuid>3c3c7043-eedc-43df-85ea-e7752306cd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>b60f6bff-4d10-4146-8d79-5330760f66e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'INFORMATION' or . = 'INFORMATION')]</value>
      <webElementGuid>73e72bc8-1b1d-41fa-8ee6-efd9249f955e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
