<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_wp-image-27826</name>
   <tag></tag>
   <elementGuidId>7939ef37-743f-4e67-918e-70cb81749401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/div[6]/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-27826</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>04780273-d510-49a7-939b-e371e6fc188f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/10/cane-basket-diwali2.jpg</value>
      <webElementGuid>1b6912fa-e74e-4816-aa75-18dc0517df27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-27826</value>
      <webElementGuid>4780825d-13d3-4986-9e93-0fdf00482e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;page-description&quot;]/div[@class=&quot;wp-block-image&quot;]/figure[@class=&quot;aligncenter size-full&quot;]/a[1]/img[@class=&quot;wp-image-27826&quot;]</value>
      <webElementGuid>7c6ea5fd-07ea-4cb2-852d-fa193691a0f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/div[6]/figure/a/img</value>
      <webElementGuid>81820033-16e4-4d5f-9ba3-ed41857702e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/10/cane-basket-diwali2.jpg')]</value>
      <webElementGuid>614448ea-78db-428f-8112-0b15f4b015ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/figure/a/img</value>
      <webElementGuid>4692a0cb-fd52-48b9-b150-dd6e228cd60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/10/cane-basket-diwali2.jpg']</value>
      <webElementGuid>d9889073-ddea-40f3-a242-1a8d00fd5812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
