<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_E-mail id</name>
   <tag></tag>
   <elementGuidId>c922e280-217f-4a2b-ae27-f5a128d5ce7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-9']/strong[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>ba5dbe8d-17a1-4f06-864a-fe267e77523b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-mail id</value>
      <webElementGuid>5a850951-e509-4ca5-ad53-5d8853e2ab3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-9&quot;)/strong[2]</value>
      <webElementGuid>8c0e21a0-7513-4067-83e5-5d0e45c5e0b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-9']/strong[2]</value>
      <webElementGuid>7de7eeed-7eda-483a-9847-6af488ced3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong[2]</value>
      <webElementGuid>457c40f1-0da7-494d-a4d3-bf20580c85d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'E-mail id' or . = 'E-mail id')]</value>
      <webElementGuid>2654b4c6-1f3c-4eb5-bf6f-18604f804664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
