<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blankets  Quilts</name>
   <tag></tag>
   <elementGuidId>b9cde268-058b-45b8-82cb-027d9cb459fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26715']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26715 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b05b4074-eef0-401a-890d-bbf2c92087ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/blankets-quilts/</value>
      <webElementGuid>35e1e593-614e-43e4-80d6-74ea4e8b2394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blankets &amp; Quilts</value>
      <webElementGuid>65bc729b-a74a-40f2-8c3a-df533e23b55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26715&quot;)/a[1]</value>
      <webElementGuid>51145b06-e3db-4ecf-b6ca-415c5872d9cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26715']/a</value>
      <webElementGuid>6121e410-9c88-4f99-ae63-b2820c4f0af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blankets &amp; Quilts')]</value>
      <webElementGuid>2d5ccc5d-f8ae-4344-b93b-5409c273592d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/blankets-quilts/')]</value>
      <webElementGuid>8da69421-fe94-4f9d-80e4-df0175b690aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[4]/a</value>
      <webElementGuid>96f009de-7ded-4009-952e-c67ed9258475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/blankets-quilts/' and (text() = 'Blankets &amp; Quilts' or . = 'Blankets &amp; Quilts')]</value>
      <webElementGuid>8d742612-fc38-4dff-bc0f-df989966c1d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
