<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_clutches</name>
   <tag></tag>
   <elementGuidId>6ffafd94-17c6-4879-8c89-d23ffccfeb01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26721']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26721 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9551a4df-75e6-4a32-8789-8cd695724fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/clutches/</value>
      <webElementGuid>ea3393e8-afb4-498c-a9c2-51e24355f700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>clutches</value>
      <webElementGuid>432d3f64-9d80-4929-a825-e7d559c27c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26721&quot;)/a[1]</value>
      <webElementGuid>18d9c69a-c913-4d78-adc9-14c0d991f166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26721']/a</value>
      <webElementGuid>96b78c8a-ff0b-40a4-96c6-e469913b8364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'clutches')]</value>
      <webElementGuid>8d13440b-4c0b-458c-8456-5f7c3fa664d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/clutches/')]</value>
      <webElementGuid>3ba1044a-7631-432b-a3af-c97b7ca11f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[4]/a</value>
      <webElementGuid>6fad8a37-0be4-412f-a64e-5dfd62f639ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/clutches/' and (text() = 'clutches' or . = 'clutches')]</value>
      <webElementGuid>e159daec-1993-47f7-a5c4-b383deae1514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
