<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outdoor Furniture</name>
   <tag></tag>
   <elementGuidId>b0d3ad8f-2071-42f1-bca7-faccbe7e8859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26702']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26702 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e3afee0-92ea-4a5a-a1bb-fad1b1680795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/outdoor-furniture/</value>
      <webElementGuid>7ad52b85-2163-4a53-832b-c27270af1275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outdoor Furniture</value>
      <webElementGuid>bb378a0f-c6d7-4203-aea6-095efbd98ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26702&quot;)/a[1]</value>
      <webElementGuid>a4cf174d-272a-4197-abc7-be086997b8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26702']/a</value>
      <webElementGuid>cea7a534-e2aa-41d7-8b00-ccc369392bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Outdoor Furniture')]</value>
      <webElementGuid>078f6c84-9fc6-42f3-bdea-ab326175dc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/outdoor-furniture/')]</value>
      <webElementGuid>cb625507-d620-478b-8e43-1b7c6b62ee00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>c037a78d-d24b-4ab5-9e4d-0e45140e1575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/outdoor-furniture/' and (text() = 'Outdoor Furniture' or . = 'Outdoor Furniture')]</value>
      <webElementGuid>2fc95d07-fb28-4a6e-8da5-e9380b5ce85b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
