<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Round Tapestry</name>
   <tag></tag>
   <elementGuidId>ea1e2f47-2572-4d26-b28e-981c6f5aafb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26727']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26727 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47228fde-f968-4e3b-a8f9-8f5cea7aab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/round-tapestry/</value>
      <webElementGuid>34daa912-5255-43a1-96d9-e2d8beee1fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Round Tapestry</value>
      <webElementGuid>0616c2c9-f0fd-47ef-9095-25b55787a70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26727&quot;)/a[1]</value>
      <webElementGuid>6a3b4e2c-8d98-4804-b628-616eaede9b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26727']/a</value>
      <webElementGuid>22188485-6e13-4a73-a610-804a51c82a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Round Tapestry')]</value>
      <webElementGuid>13795527-6323-4a55-a3a1-2431d778f018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/round-tapestry/')]</value>
      <webElementGuid>d2cc7edb-5b5d-4600-a903-d57942bb29cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/a</value>
      <webElementGuid>e1c86339-e4bd-4d56-9dcc-07df056f479b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/round-tapestry/' and (text() = 'Round Tapestry' or . = 'Round Tapestry')]</value>
      <webElementGuid>9febab55-ef86-471c-96c2-77674554d1e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
