<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Single Tapestry</name>
   <tag></tag>
   <elementGuidId>e6707bb5-8a5e-44be-b289-2e7fbc38df26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26726']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26726 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed70bd99-a4e3-453f-b34d-8ed22f9b4ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/single-tapestry/</value>
      <webElementGuid>2d33e809-8754-4d0f-8857-015310524223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single Tapestry</value>
      <webElementGuid>3024e69f-81b8-429a-ba01-9b1589f17211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26726&quot;)/a[1]</value>
      <webElementGuid>6bd3a073-dbf8-4609-bade-e8428c5a6e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26726']/a</value>
      <webElementGuid>af82af83-8d00-48ad-a7b5-763b123879b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Single Tapestry')]</value>
      <webElementGuid>7ac23242-f5ec-4252-b23b-bb0b42cc9b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/single-tapestry/')]</value>
      <webElementGuid>313a67fd-c601-49d2-ae91-8cd6164a4229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>1a8e1175-405f-43f9-9d8b-42ae748a5dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/single-tapestry/' and (text() = 'Single Tapestry' or . = 'Single Tapestry')]</value>
      <webElementGuid>fb7d5f18-af51-4a8b-9fe9-71de4dfab23a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
