<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_handbags</name>
   <tag></tag>
   <elementGuidId>7f8da073-9199-4efa-98ba-ec56b12df9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26718']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26718 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2007fd25-a69c-4ea4-b173-e3ff8c49f885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/handbags/</value>
      <webElementGuid>c4b25f73-3086-444a-82f1-8716e6c4bdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>handbags</value>
      <webElementGuid>1647f2e6-91da-4715-b8fe-fa85abe3ace5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26718&quot;)/a[1]</value>
      <webElementGuid>81bffd21-823e-4ea7-96fd-e4ca874b808e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26718']/a</value>
      <webElementGuid>ca794de2-181a-46fe-9283-e06d84fa13bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'handbags')]</value>
      <webElementGuid>ad7e3ef3-0c75-464c-912e-6eab34bf55d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/handbags/')]</value>
      <webElementGuid>df6d2349-557f-4bd0-9511-feb8cda6bc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a</value>
      <webElementGuid>ec671223-0959-45f7-854d-3c4179c6f2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/handbags/' and (text() = 'handbags' or . = 'handbags')]</value>
      <webElementGuid>8bbe8a94-68d2-4f10-9729-a72df4ec8005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
