<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-angle-right</name>
   <tag></tag>
   <elementGuidId>9b3676e8-249c-42ef-bce4-3e23e1d49df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dswbm-sliders-28180']/div[2]/div[2]/div/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bc800069-dd5e-42b2-a768-fc3cd71d9bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-right</value>
      <webElementGuid>f0db6c51-18cf-4820-9eb3-5471acd1df8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dswbm-sliders-28180&quot;)/div[@class=&quot;bx-wrapper&quot;]/div[@class=&quot;bx-controls bx-has-controls-direction&quot;]/div[@class=&quot;bx-controls-direction&quot;]/a[@class=&quot;bx-next&quot;]/i[@class=&quot;fa fa-angle-right&quot;]</value>
      <webElementGuid>3bc27bc1-370f-40c7-9693-80cec3638a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dswbm-sliders-28180']/div[2]/div[2]/div/a[2]/i</value>
      <webElementGuid>6620a8d1-f7a4-4b15-8d02-fb96561b1627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>c9c57838-5951-464f-bb44-052fe2bab105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
