<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CRAFERIA_DATADRIVEN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>26771063-0b2a-4d08-a629-54854ed8a91f</testSuiteGuid>
   <testCaseLink>
      <guid>46458def-b28c-4309-a8c0-5971c74a6e5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CRAFERIA/TC_CRAFERIA_DATADRIVEN/TC_CRAFERIA_LOGIN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23e36916-cb1e-48b6-a3ce-cdf9c85a3d45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce222451-5580-44ca-be34-0a007a09ce94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c287f526-f511-45f1-a12a-783f6dbbb4c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CRAFERIA/TC_CRAFERIA_DATADRIVEN/TC_CRAFERIA_REGISTER</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
