<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Storage Basket and Utility Baskets</name>
   <tag></tag>
   <elementGuidId>009782ad-e94d-44d9-af20-20443bf1867b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26716']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26716 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c4b06cf-8838-40fa-8af1-b3cb363adaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-storage-basket-and-utility-baskets/</value>
      <webElementGuid>4e42174b-69b1-464d-9cc2-32be57fea9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Storage Basket and Utility Baskets</value>
      <webElementGuid>f473e0b7-b5bf-481b-a79b-d8ab2d9f1824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26716&quot;)/a[1]</value>
      <webElementGuid>587e8dc9-e868-462e-8312-e3a2d5acfe86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26716']/a</value>
      <webElementGuid>873f0de3-0bbf-410f-8c2d-40fc74d06d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Storage Basket and Utility Baskets')]</value>
      <webElementGuid>59715513-9d0e-462e-a632-63b2f87279a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-storage-basket-and-utility-baskets/')]</value>
      <webElementGuid>dbe916a0-df96-4a6f-a005-4a966b48e68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[6]/a</value>
      <webElementGuid>174bd96d-9892-4c5b-9494-95703a28d983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-storage-basket-and-utility-baskets/' and (text() = 'Bamboo Storage Basket and Utility Baskets' or . = 'Bamboo Storage Basket and Utility Baskets')]</value>
      <webElementGuid>d026c13d-b2d7-4f0e-b0ab-1a8f5508e380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
