<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Laundry  Organizer Baskets</name>
   <tag></tag>
   <elementGuidId>a7a7b897-cd1e-441b-a92f-f4c43ed6d4dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26666']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26666 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b44b0bf-f4de-4573-9707-039ec0393656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-laundry-organizer-baskets/</value>
      <webElementGuid>fa29d745-12bd-4ca0-92c1-0a9a27878f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Laundry &amp; Organizer Baskets</value>
      <webElementGuid>b0c26350-3066-46a6-a4b2-c019fb845868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26666&quot;)/a[1]</value>
      <webElementGuid>d57027db-5483-4491-923c-c7d43fdc459e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26666']/a</value>
      <webElementGuid>8dbf4ac3-17c7-49d7-9c0d-6bd3988d7582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Laundry &amp; Organizer Baskets')]</value>
      <webElementGuid>ecf3d372-1975-4585-87f6-2f20b5373f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-laundry-organizer-baskets/')]</value>
      <webElementGuid>28b5d9c0-f2fe-4c21-b4b2-ce4fe4bbffeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>6b9fa9f8-6220-4b96-a22c-acf45ac019f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-laundry-organizer-baskets/' and (text() = 'Bamboo Laundry &amp; Organizer Baskets' or . = 'Bamboo Laundry &amp; Organizer Baskets')]</value>
      <webElementGuid>51264e21-2799-48aa-b6bf-fb6d8ba0c9f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
