<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cushions</name>
   <tag></tag>
   <elementGuidId>17c39192-234b-4269-8521-a5dd3a666ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26710']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26710 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>080e5c88-1821-4e4e-bc09-341573194ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/cushions/</value>
      <webElementGuid>c9df08bf-1f8c-4ba3-9d8e-722e8e8fa568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cushions</value>
      <webElementGuid>37dbbae6-1809-4e8f-9f10-a14de0eb46ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26710&quot;)/a[1]</value>
      <webElementGuid>4ebc5154-f4ba-4d8e-a676-d50f441ecb67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26710']/a</value>
      <webElementGuid>5b3d2532-89fc-4d46-9317-27f84d1b1f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cushions')]</value>
      <webElementGuid>a4b1c2b8-47b9-4be7-aaa1-27cdad73546c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/cushions/')]</value>
      <webElementGuid>d4cf27a3-58e4-458e-b529-6678c5ab2720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/a</value>
      <webElementGuid>861b9f0c-1ef1-402d-b27f-59d0e597bd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/cushions/' and (text() = 'Cushions' or . = 'Cushions')]</value>
      <webElementGuid>58011b5b-c4da-418e-9b19-f44421d4e799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
