<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Furnishings</name>
   <tag></tag>
   <elementGuidId>1291fea6-e0f8-4fd7-b36a-3caeee1f4dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26709']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26709 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed9c31ac-5107-4fab-be16-40d993a6a0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/furnishings/</value>
      <webElementGuid>97ec00a1-7043-4c33-8305-e790db497b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>cdd75ae4-2926-4d32-ae11-6fa9483d7f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Furnishings</value>
      <webElementGuid>74a9f9ed-26e4-4e4b-8c46-c3c5de548344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26709&quot;)/a[1]</value>
      <webElementGuid>7a17254e-bad8-4d53-ad78-fdc8c6a312fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26709']/a</value>
      <webElementGuid>1ebeb7fd-305c-4ca1-a427-f6e1b360c699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Furnishings')]</value>
      <webElementGuid>65b05fbc-0fd5-4862-ab23-d6c0102dc893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/furnishings/')]</value>
      <webElementGuid>8c1e66ce-b5c9-4418-99b0-d3f929c3d53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>230ea1bf-3ee0-4513-a017-334ea9854f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/furnishings/' and (text() = 'Furnishings' or . = 'Furnishings')]</value>
      <webElementGuid>b2a981fd-7b5e-4dc2-a5ac-96f8ab823adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
