<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Mudha</name>
   <tag></tag>
   <elementGuidId>b66e1d0f-140b-41a1-82aa-0f64b9156ae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26663']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26663 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a68c107c-11b1-4016-af43-6bbcd19f0991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-mudha/</value>
      <webElementGuid>ae98ee0c-9857-4234-8cc5-5d8065586950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Mudha</value>
      <webElementGuid>3c3337b3-54e0-4e67-a353-81a31811ca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26663&quot;)/a[1]</value>
      <webElementGuid>712df454-3561-47be-866d-175c2e6eb83b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26663']/a</value>
      <webElementGuid>9391752c-a64c-4315-8b66-97100f0caad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Mudha')]</value>
      <webElementGuid>2d7b25b8-d6a2-4385-8f65-d2e7b229373c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-mudha/')]</value>
      <webElementGuid>adff06f2-a96b-44b9-bce9-f61c3291dd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul/li[2]/a</value>
      <webElementGuid>a616ad4f-f227-434d-bcda-6befa591e242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-mudha/' and (text() = 'Bamboo Mudha' or . = 'Bamboo Mudha')]</value>
      <webElementGuid>89084e60-fdab-45ef-bdc3-91c700123647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
