<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Tables</name>
   <tag></tag>
   <elementGuidId>921efa56-7542-417e-a407-99f1da7376c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26664']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26664 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec024e9d-1901-4f5e-b19a-626885afd472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-tables/</value>
      <webElementGuid>bf5789ab-2c6e-4168-8791-65e6f2b884eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Tables</value>
      <webElementGuid>d9040c8b-0d97-41e4-a939-42c16f3ce17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26664&quot;)/a[1]</value>
      <webElementGuid>463e0d9e-d419-4e32-a809-5986a7456381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26664']/a</value>
      <webElementGuid>88644a16-f981-49e1-910e-0688a1e613fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Tables')]</value>
      <webElementGuid>2102d736-7ec6-46d8-ae4c-0c1b5b45d41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-tables/')]</value>
      <webElementGuid>59a94751-8864-4ae3-8455-3fd72b6e80cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul/li[3]/a</value>
      <webElementGuid>ab24ffc0-f2a6-4300-b086-86594fce3956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-tables/' and (text() = 'Bamboo Tables' or . = 'Bamboo Tables')]</value>
      <webElementGuid>c8d4e000-d695-4b02-86ea-dc8a03449b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
