<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sling bags</name>
   <tag></tag>
   <elementGuidId>70dedaf6-48a6-433a-a210-bbb9045fccd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26720']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26720 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e4ec21cd-10de-404c-86f3-0f9d3c90af73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/sling-bags/</value>
      <webElementGuid>3cb238ce-89f5-4764-ba9e-f8a508ee7256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sling bags</value>
      <webElementGuid>2409784f-8f6e-4967-b063-25736626a7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26720&quot;)/a[1]</value>
      <webElementGuid>2ef2d9d3-d7e7-418d-9f78-d08b6c3e3101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26720']/a</value>
      <webElementGuid>9937ca3f-02dc-4c2a-9f78-9e360579ded3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sling bags')]</value>
      <webElementGuid>987e7004-2663-48c1-8a2e-23875f17c59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/sling-bags/')]</value>
      <webElementGuid>d90de064-4137-4aca-93e7-6c35c87d0cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li[3]/a</value>
      <webElementGuid>2477f23f-df96-48f1-9fde-b63542c7aecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/sling-bags/' and (text() = 'Sling bags' or . = 'Sling bags')]</value>
      <webElementGuid>ca069783-d23d-42a1-9796-c6186924b139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
