<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Showpieces  Figurines</name>
   <tag></tag>
   <elementGuidId>be3493c8-fe5b-46b4-9e9b-bc9c936df6ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26678']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26678 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd7bee6d-bc99-46bf-a6ce-ab4fd156bc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/showpieces-figurines/</value>
      <webElementGuid>d65df67f-a24e-4e05-add1-c6eb759f54d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showpieces &amp; Figurines</value>
      <webElementGuid>c0acf9bd-3ab5-46c8-8d04-7f22b773ac21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26678&quot;)/a[1]</value>
      <webElementGuid>b746eb63-de2a-4ae7-9c00-d8874806ad8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26678']/a</value>
      <webElementGuid>6c6ff3b0-9a25-4536-a937-8381f0934104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Showpieces &amp; Figurines')]</value>
      <webElementGuid>96fff490-bb56-4582-94b1-647cd911c202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/showpieces-figurines/')]</value>
      <webElementGuid>add6865a-077e-4f1b-931e-91450dc1f704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>6c0af123-e17f-4b98-91c9-7804ec0ad3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/showpieces-figurines/' and (text() = 'Showpieces &amp; Figurines' or . = 'Showpieces &amp; Figurines')]</value>
      <webElementGuid>930da85c-8b19-4211-b22b-d86501913e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
